# Generated by Django 3.1.5 on 2021-01-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
